=== AgMarciniak/icplayer/addons/tools/addon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://icplayer.com" xmlns="http://icplayer.com" elementFormDefault="qualified">

<xs:element name="addon">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="model">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="type" type="xs:string" use="required"/>
								<xs:attribute name="displayName" type="xs:string"/>
								<xs:attribute name="isLocalized">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="True"/>
											<xs:enumeration value="False"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>

</xs:schema>

=== AgMarciniak/icplayer/addons/Maze/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Maze' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="width" nameLabel="Maze_property_width" type="string"/>
		<property name="height" nameLabel="Maze_property_height" type="string"/>
		<property name="numberOfMazes" nameLabel="Maze_property_number_of_mazes" type="string"/>
		<property name="gameMode" nameLabel="Maze_property_game_mode" type="{Diamond,Letters}"/>

		<property name="questions" nameLabel="Maze_property_questions" type="list">
            <property name="question" nameLabel="Maze_property_questions_question" type="html" />
            <property name="answer" nameLabel="Maze_property_questions_answer" type="string"/>
			<property name="letter" nameLabel="Maze_property_questions_letter" type="string"/>
			<property name="mazeId" nameLabel="Maze_property_questions_maze_number" type="string"/>
        </property>
		<property name="isDisabled" nameLabel="Maze_property_is_disabled" type="boolean"/>
		<property name="hideControlPanel" nameLabel="Maze_property_hide_control_panel" type="boolean" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/video/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='video' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Files' type='list'>
			<property name="Ogg video" displayName="Ogv video" type="file" />
			<property name="MP4 video" type="file" />
			<property name="WebM video" type="file" />
			<property name="Subtitles" type="text" isLocalized="true" />
			<property name="Poster" type="image" />
			<property name="ID" type="string" />
		</property>
		<property name="Show video" type="string" />
		<property name="Narration" type="narration" isLocalized="true" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/PseudoCode_Console/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='PseudoCode_Console' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="functionsList" nameLabel="PseudoCode_Console_property_functions_list" type="list">
            <property name="name" nameLabel="PseudoCode_Console_property_functions_name" type="string" />
            <property name="body" nameLabel="PseudoCode_Console_property_functions_body" type="text" />
        </property>
        <property name="methodsList" nameLabel="PseudoCode_Console_property_methods_list" type="list">
            <property name="objectName" nameLabel="PseudoCode_Console_property_object_name" type="{Number,String,Array}"/>
            <property name="methodName" nameLabel="PseudoCode_Console_property_method_name" type="string"/>
            <property name="methodBody" nameLabel="PseudoCode_Console_property_method_body" type="text"/>
        </property>
        <property name="default_aliases" nameLabel="PseudoCode_Code_property_default_aliases" type="text" isDefault="true"/>
        <property name="isNotActivity" nameLabel="PseudoCode_Console_property_is_not_activity" type="boolean" />
        <property name="runUserCode" nameLabel="PseudoCode_Console_property_run_user_code" type="boolean" />
        <property name="runParameters" nameLabel="PseudoCode_Console_property_run_parameters" type="list">
            <property name="value" nameLabel="PseudoCode_Console_property_parameters_value" type="string" />
        </property>
        <property name="maxTimeForAnswer" nameLabel="PseudoCode_Console_property_answer_max_timeout" type="string" />
        <property name="answerCode" nameLabel="PseudoCode_Console_property_answer_code" type="text" />

    </model>
</addon>

=== AgMarciniak/icplayer/addons/Clock/src/addon.xml
<?xml version='1.0' encoding='UTF-8'?>
<addon id="Clock" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="TimeStandard" type="{24H,12H}"/>
		<property name="InitialTime" type="string"/>
		<property name="TimeStep" type="string" displayName="Step (minutes)"/>
		<property name="ShowClockLabels" type="boolean"/>
		<property name="ActiveHand" type="{Both,HourHand,MinuteHand}"/>
		<property name="SynchronizeHands" type="{None, Min with Hour, Both}"/>
		<property name="Images" type="list">
			<property name="Background" type="image"/>
		</property>
		<property name="CorrectAnswer" type="string"/>
		<property name="isDisable" type="boolean"/>
		<property name="isActivity" type="boolean"/>
	</model>
</addon>

=== AgMarciniak/icplayer/addons/Image_Viewer_Button_Controlled_Public/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Image_Viewer_Button_Controlled_Public' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Image' type='file' />
		<property name="Frames" type="string" />
		<property name="Frame size" type="{Original, Keep aspect ratio, Stretch}" />
		<property name="Sounds" type="list">
			<property name="MP3 sound" type="file" />
			<property name="OGG sound" type="file" />
			<property name="AAC sound" type="file" />
		</property>
		<property name="Frame names" type="list">
			<property name="name" type="string" />
			<property name="frame" type="string" />
		</property>
		<property name="isClickDisabled" type="boolean" />
		<property name="Labels" type="list">
			<property name="Text" type="string" isLocalized="true" />
			<property name="Top" type="string" />
			<property name="Left" type="string" />
			<property name="Frames" type="string" />
		</property>
		<property name="Show frame" type="string" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/Viewer_3D/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Viewer_3D' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='OBJ File' type='file' />
		<property name='MTL File' type='file' />
		<property name="Initial Rotation X" type="string" />
		<property name="Initial Rotation Y" type="string" />
		<property name="Initial Rotation Z" type="string" />
		<property name="Model Color" type="string" />
		<property name="Background Color 1" type="string" />
		<property name="Background Color 2" type="string" />
		<property name="Render Mode" type="{Smooth,Points,Wireframe,Flat}" />
	</model>
</addon>
