=== AgMarciniak/icplayer/addons/tools/addon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://icplayer.com" xmlns="http://icplayer.com" elementFormDefault="qualified">

<xs:element name="addon">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="model">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="type" type="xs:string" use="required"/>
								<xs:attribute name="displayName" type="xs:string"/>
								<xs:attribute name="isLocalized">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="True"/>
											<xs:enumeration value="False"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>

</xs:schema>

=== AgMarciniak/icplayer/addons/Shape_Tracing/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>
<addon id='Shape_Tracing' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="Shape image" type="file" />
        <property name="Show Shape image" type="boolean" />
        <property name="Hide Shape image on check" type="boolean" />
        <property name="Show Boundaries (editor)" type="boolean" />
        <property name="Background image" type="file" />
        <property name="Correct number of lines" type="string" />
        <property name="Points' coordinates" type="text" />
        <property name="isPointsOrder" displayName="Mind points' order" type="boolean" />
        <property name="Color" type="string" />
        <property name="Pen Thickness" displayName="Thickness" type="string" />
        <property name="Opacity" type="string" />
        <property name="Border" type="string" />
        <property name="Correct Answer Image" type="file" />
    </model>
</addon>

=== AgMarciniak/icplayer/addons/Standard_Shapes/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Standard_Shapes' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Shape' type='{Line, Square, Rectangle, Circle, Ellipse}' />
		<property name="Rotation angle" type="string" />
		<property name="Stroke width" type="string" />
		<property name="Stroke color" type="string" />
		<property name="Corners rounding" type="boolean" />
		<property name="Line ending" type="{None, Circles, Arrows, None - Arrow, None - Circle, Circle - Arrow}" />
		<property name="Stroke opacity" type="string" />
		<property name="Fill color" type="string" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/PointsLines/src/addon.xml
<?xml version='1.0' encoding='UTF-8'?>
<addon id="PointsLines" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Points" type="text" displayName="Points' coordinates"/>
		<property name="Indexes" type="text" displayName="Points' indexes"/>
		<property name="Starting lines" type="text" displayName="Starting lines"/>
		<property name="Lines" type="text" displayName="Answer"/>
		<property name="Is activity" type="boolean"/>
		<property name="Is disabled" type="boolean"/>
	</model>
</addon>

=== AgMarciniak/icplayer/addons/multiplegap/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='multiplegap' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Orientation' type='{horizontal, vertical}' />
		<property name="Source type" type="{images, texts}" />
		<property name="Items" type="list">
			<property name="Answer ID" type="string" />
		</property>
		<property name="Item width" type="string" />
		<property name="Item height" type="string" />
		<property name="Item spacing" type="string" />
		<property name="Stretch images?" type="boolean" />
		<property name="Item horizontal align" type="{none, left, right, center}" />
		<property name="Item vertical align" type="{none, top, bottom, center}" />
		<property name="Maximum item count" type="string" />
		<property name="Is not an activity" type="boolean" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/Audio/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Audio' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="mp3" nameLabel="Audio_property_mp3" type="file" />
		<property name="ogg" nameLabel="Audio_property_ogg" type="file" />
		<property name="defaultControls" nameLabel="Audio_property_default_controls" type="boolean" />
        <property name="useBrowserControls" nameLabel="Audio_property_use_browser_controls" type="boolean" />
		<property name="displayTime" nameLabel="Audio_property_display_time" type="boolean" />
		<property name="enableLoop" nameLabel="Audio_property_enable_loop" type="boolean" />
		<property name="Narration" nameLabel="Audio_property_narration" type="narration" isLocalized="true" />
		<property name="onEnd" nameLabel="Audio_property_on_end" type="event"/>
	</model>
</addon>

=== AgMarciniak/icplayer/addons/IWB_Toolbar/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='IWB_Toolbar' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
        <property name="floatingImages" displayName="Floating Images" nameLabel="IWB_Toolbar_property_floating_images" type="list">
            <property name="Image" nameLabel="IWB_Toolbar_property_image" type="file" />
        </property>
        <property name="widthWhenOpened" displayName="Width When Opened" nameLabel="IWB_Toolbar_property_width_when_opened" type="string" />
        <property name="Fixed Position" nameLabel="IWB_Toolbar_property_fixed_position" type="boolean"/>

        <property name="forPen" displayName="Show for pen" nameLabel="IWB_Toolbar_property_for_pen" type="{---, Color panel, Thickness panel}" />
        <property name="forMarker" displayName="Show for marker" nameLabel="IWB_Toolbar_property_for_marker" type="{---, Color panel, Thickness panel}" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/EdgeAnimation/src/addon.xml
<?xml version='1.0' encoding='UTF-8'?>
<addon id="EdgeAnimation" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Animations" type="list">
			<property name="compositionClass" type="string" displayName="Composition Class"/>
			<property name="edgeFile" type="file" displayName="edge.js"/>
			<property name="edgeActionsFile" type="file" displayName="edgeActions.js"/>
		</property>
		<property name="Images" type="list">
			<property name="animationItem" type="string" displayName="Animation Item Number"/>
			<property name="elementId" type="string" displayName="Edge element IDs (csv)"/>
			<property name="imageFile" type="image" displayName="Image File"/>
		</property>
		<property name="initialAnimation" type="string" displayName="Initial Animation"/>
		<property name="Narration" type="text"/>
	</model>
</addon>

=== AgMarciniak/icplayer/addons/gamememo/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='gamememo' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Pairs' type='list'>
			<property name="A (text)" type="string" isLocalized="true" />
			<property name="A (image)" type="file" />
			<property name="B (text)" type="string" isLocalized="true" />
			<property name="B (image)" type="file" />
		</property>
		<property name="Columns" type="string" />
		<property name="Rows" type="string" />
		<property name="Use two styles for cards" type="boolean" />
		<property name="Image for style A" type="image" />
		<property name="Image for style B" type="image" />
		<property name="Keep cards aspect ratio" type="boolean" />
		<property name="Show cards for preview" type="boolean" />
	</model>
</addon>
