=== AgMarciniak/icplayer/addons/tools/addon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://icplayer.com" xmlns="http://icplayer.com" elementFormDefault="qualified">

<xs:element name="addon">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="model">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="property" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="type" type="xs:string" use="required"/>
								<xs:attribute name="displayName" type="xs:string"/>
								<xs:attribute name="isLocalized">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="True"/>
											<xs:enumeration value="False"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
</xs:element>

</xs:schema>

=== AgMarciniak/icplayer/addons/ConnectingDots/src/addon.xml
<?xml version='1.0' encoding='UTF-8'?>
<addon id="ConnectingDots" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Dots" type="text" displayName="Dots' coordinates"/>
		<property name="Indexes" type="text" displayName="Dots' indexes"/>
		<property name="Is activity" type="boolean"/>
		<property name="Time" type="string" displayName="Animation time"/>
		<property name="Image A" type="image" displayName="Start image"/>
		<property name="Image B" type="image" displayName="End image"/>
		<property name="Is disabled" type="boolean"/>
	</model>
</addon>

=== AgMarciniak/icplayer/addons/Lesson_Progress/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Lesson_Progress' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
        <property name="Show_Progress_Bar" displayName="Show Progress Bar" type="boolean" />
        <property name="Show_Checks" displayName="Show Checks" type="boolean" />
        <property name="Show_Correct_Answers" displayName="Show Correct Answers" type="boolean" />
        <property name="Show_Errors" displayName="Show Errors" type="boolean" />
        <property name="Show_Mistakes" displayName="Show Mistakes" type="boolean" />
        <property name="Show_All_Answers" displayName="Show All Answers" type="boolean" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/Grid_Scene/src/addon.xml
<?xml version="1.0" encoding="UTF-8" ?>

<addon id="Grid_Scene" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
        <property name="Rows" nameLabel="Grid_Scene_property_rows" type="string" />
        <property name="Columns" nameLabel="Grid_Scene_property_columns" type="string" />
        <property name="Color" nameLabel="Grid_Scene_property_color" type="string" />
        <property name="delay" nameLabel="Grid_Scene_property_delay" type="string" />
        <property name="labels" nameLabel="Grid_Scene_property_labels" type="text" />
        <property name="commands" nameLabel="Grid_Scene_property_commands" type="list">
            <property name="command_name" nameLabel="Grid_Scene_property_command_name" type="string"/>
            <property name="command_arguments" nameLabel="Grid_Scene_property_command_arguments" type="string"/>
            <property name="command_code" nameLabel="Grid_Scene_property_command_code" type="text"/>
        </property>
        <property name="excluded_commands" nameLabel="Grid_Scene_property_exclude_commands" type="list" >
            <property name="command_name" nameLabel="Grid_Scene_property_exclude_command_name" type="string"/>
            <property name="command_is_excluded" nameLabel="Grid_Scene_property_exclude_command_is_excluded" type="boolean" />
        </property>

	</model>
</addon>

=== AgMarciniak/icplayer/addons/graph/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='graph' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
        <property name="isNotActivity" displayName="Is not an activity" type="boolean" />
		<property name="X axis description" type="string" isLocalized="true" />
		<property name="Show X axis bars descriptions" type="boolean" />
		<property name="X axis bars descriptions" type="list">
			<property name="Description" type="string" isLocalized="true" />
		</property>
		<property name="Show X axis series descriptions" type="boolean" />
		<property name="X axis series descriptions" type="list">
			<property name="Description" type="string" isLocalized="true" />
		</property>
		<property name="Y axis description" type="string" isLocalized="true" />
		<property name="Y axis maximum value" type="string" />
		<property name="Y axis minimum value" type="string" />
		<property name="Y axis grid step" type="string" />
		<property name="Interactive" type="boolean" />
		<property name="Interactive step" type="string" />
		<property name="Data" type="text" />
		<property name="Answers" type="list">
			<property name="Answer" type="string" />
		</property>
		<property name="Series colors" type="list">
			<property name="Color" type="string" />
		</property>
		<property name="Decimal separator" type="string" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/eKeyboard/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='eKeyboard' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
        <property name="workWith" displayName="Work With" type="text" />
        <property name="layoutType" displayName="Layout Type"
                  type="{Numeric, French (Special Characters), German (Special Characters), Spanish (Special Characters), Custom}" />
        <property name="customLayout" displayName="Custom Layout" type="text" />
        <property name="positionMy" displayName="Position My" type="string" />
        <property name="positionAt" displayName="Position At" type="string" />
        <property name="maxCharacters" displayName="Max Characters" type="string" />
        <property name="noOpenOnFocus" displayName="Don't Open On Focus" type="boolean" />
        <property name="lockStandardKeyboardInput" displayName="Lock Standard Keyboard Input" type="boolean" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/DrawingSmartPen/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id="DrawingSmartPen" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
        <property name="SmartPen" displayName="LearnPen" type="boolean" />
        <property name="Colors" type="text" />
        <property name="Thickness" type="text" />
        <property name="Opacity" type="text" />

        <property name="Squeeze limits" type="string" />
        <property name="Squeeze limits interpretation" type="{Separately, Together}" />
        <property name="Pressure limits" type="string" />

        <property name="Events" type="list">
            <property name="Sensor" type="string" />
            <property name="Reaction scope" type="string" />
            <property name="Item" type="string" />
            <property name="Value" type="string" />
            <property name="Score" type="string" />
        </property>

        <property name="Mirror" type="boolean" />
        <property name="Background color" type="string" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/Slider/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Slider' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='ImageElement' type='image' />
		<property name="Orientation" type="{Landscape, Portrait}" />
		<property name="Stepwise" type="boolean" />
		<property name="StepsCount" type="string" />
		<property name="InitialStep" type="string" />
		<property name="onStepChange" type="event" />
		<property name="Block in error checking mode" type="boolean" />
	</model>
</addon>

=== AgMarciniak/icplayer/addons/Fractions/src/addon.xml
<?xml version='1.0' encoding='UTF-8'?>
<addon id="Fractions" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Figure" type="{---,Rectangular,Circle}"/>
		<property name="RectHorizontal" type="string" />
		<property name="RectVertical" type="string" />
		<property name="CircleParts" type="string" />
		<property name="Correct" type="string" />
		<property name="selectedParts" type="string" />
		<property name="selectionColor" type="string" />
		<property name="emptyColor" type="string" />
		<property name="strokeColor" type="string" />
		<property name="strokeWidth" type="string" />
		<property name="isNotActivity" type="boolean"/>
		<property name="isDisable" type="boolean"/>
	</model>
</addon>
